version: '3'

services:
    rabbitmq:
        image: rabbitmq:3
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq/
            - rabbitmq-logs:/var/log/rabbitmq
        networks:
            - backend

    mongo:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - mongodb-data:/data/db

    api:
        build: api
        ports: 
            - 4000:4000

networks:
    backend:
        driver: bridge

volumes:
    rabbitmq-logs:
    rabbitmq-data:
    mongodb-data:
